// FrontendReact/together-app/src/routes/MyProfile/ContentTabs/MyAccount/MyAccount.tsx
import TextField from "@mui/material/TextField";
import { Divider } from "@mui/material";
import InputAdornment from "@mui/material/InputAdornment";
import AccountCircle from "@mui/icons-material/AccountCircle";
import EmailIcon from "@mui/icons-material/Email";
import LocalPhoneIcon from "@mui/icons-material/LocalPhone";
import LocationCityIcon from "@mui/icons-material/LocationCity";
import PublicIcon from "@mui/icons-material/Public";
import Button from "@mui/material/Button";
import ProfilePic from "../../../../assets/images/profile-pic.jpeg";
import Card from "@mui/material/Card";
import { useEffect, useState } from "react";
import { getUser } from "./hooks/getUser";
import { updateUser } from "./hooks/updateUser";
import IUserInfo from "../../../../api/models/UserInfo";

export function MyAccount() {
  const [userInfo, setUserInfo] = useState<IUserInfo | undefined>(undefined);

  useEffect(() => {
    const fetchUser = async () => {
      try {
        const userData = await getUser()();
        setUserInfo(userData || undefined);
      } catch (error) {
        console.error("Failed to fetch user information:", error);
        setUserInfo(undefined);
      }
    };

    fetchUser();
  }, []);

  const handleSave = () => {
    if (userInfo) {
      updateUser(userInfo);
    }
  };
  
  const handleInputChange = (key: keyof IUserInfo, value: string) => {
    if (userInfo) {
      setUserInfo((prevUserInfo) => ({
        ...prevUserInfo!,
        [key]: value,
      }));
    }
  };

  if (!userInfo) {
    return <div>Loading...</div>;
  }

  return (
    <Card sx={{ padding: 3, paddingBottom: 1 }} variant="outlined">
      <div className="rounded-3 w-100 pt-2 pb-2">
        <div className="d-flex flex-column justify-content-between">
          <div className="d-flex flex-column justify-content-center align-items-center pb-3">
            <img
              src={ProfilePic}
              className="rounded-circle object-fit-cover"
              width="100"
              height="100"
              alt="profile-pic"
              style={{ objectFit: "cover" }}
            />
          </div>
          <Divider />
          <div className="pt-4 d-flex flex-column gap-1">
            <div className="d-flex flex-row gap-3">
              <div>
                <p className="fs-6 fw-normal m-0 text-dark w-100 mt-1 mb-2">
                  Name
                </p>
                <TextField
                  id="input-first-name"
                  label="First Name"
                  variant="outlined"
                  InputProps={{
                    startAdornment: (
                      <InputAdornment position="start">
                        <AccountCircle />
                      </InputAdornment>
                    ),
                  }}
                  value={userInfo.name}
                  onChange={(e) => handleInputChange("name", e.target.value)}
                />
              </div>
              <div>
                <p className="fs-6 fw-normal m-0 text-dark w-100 mt-1 mb-2">
                  Last Name
                </p>
                <TextField
                  id="input-with-icon-textfield"
                  label="Last Name"
                  variant="outlined"
                  InputProps={{
                    startAdornment: (
                      <InputAdornment position="start">
                        <AccountCircle />
                      </InputAdornment>
                    ),
                  }}
                  value={userInfo.surname}
                  onChange={(e) => handleInputChange("surname", e.target.value)}
                />
              </div>
            </div>
            <div className="d-flex flex-row gap-3">
              <div>
                <p className="fs-6 fw-normal m-0 text-dark w-100 mt-2 mb-2">
                  Email
                </p>
                <TextField
                  id="input-with-icon-textfield"
                  label="Email"
                  variant="outlined"
                  InputProps={{
                    startAdornment: (
                      <InputAdornment position="start">
                        <EmailIcon />
                      </InputAdornment>
                    ),
                  }}
                  value={userInfo.email}
                  onChange={(e) => handleInputChange("email", e.target.value)}
                />
              </div>
              <div>
                <p className="fs-6 fw-normal m-0 text-dark w-100 mt-2 mb-2">
                  Phone
                </p>
                <TextField
                  id="input-with-icon-textfield"
                  label="Phone"
                  variant="outlined"
                  InputProps={{
                    startAdornment: (
                      <InputAdornment position="start">
                        <LocalPhoneIcon />
                      </InputAdornment>
                    ),
                  }}
                  value={userInfo.phoneNumber}
                  onChange={(e) =>
                    handleInputChange("phoneNumber", e.target.value)
                  }
                />
              </div>
            </div>
            <div className="d-flex flex-row gap-3">
              <div>
                <p className="fs-6 fw-normal m-0 text-dark w-100 mt-2 mb-2">
                  City
                </p>
                <TextField
                  id="input-with-icon-textfield"
                  label="City"
                  variant="outlined"
                  InputProps={{
                    startAdornment: (
                      <InputAdornment position="start">
                        <LocationCityIcon />
                      </InputAdornment>
                    ),
                  }}
                  value={userInfo.city}
                  onChange={(e) => handleInputChange("city", e.target.value)}
                />
              </div>
              <div>
                <p className="fs-6 fw-normal m-0 text-dark w-100 mt-2 mb-2">
                  Country
                </p>
                <TextField
                  id="input-with-icon-textfield"
                  label="Country"
                  variant="outlined"
                  InputProps={{
                    startAdornment: (
                      <InputAdornment position="start">
                        <PublicIcon />
                      </InputAdornment>
                    ),
                  }}
                  value={userInfo.country}
                  onChange={(e) => handleInputChange("country", e.target.value)}
                />
              </div>
            </div>
          </div>
          <div className="text-center mt-2">
            <Button
              variant="contained"
              className="mt-2"
              onClick={() => handleSave()}
            >
              Save Changes
            </Button>
          </div>
        </div>
      </div>
    </Card>
  );
}

// FrontendAngular/togetherapp/src/app/my-account/my-account-home/my-account.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatDividerModule } from '@angular/material/divider';
import { MatSelectModule } from '@angular/material/select';

@Component({
  selector: 'togetherapp-my-account',
  standalone: true,
  imports: [CommonModule, MatIconModule, MatButtonModule, MatFormFieldModule, MatInputModule, MatDividerModule, MatSelectModule],
  templateUrl: './my-account.component.html',
  styleUrl: './my-account.component.scss',
})
export class MyAccountComponent {
  selectedFile: any

  onFileSelected(event: any) {
    this.selectedFile = event.target.files[0];
    console.log(this.selectedFile);
  }
}

<div class="rounded-3 w-100 pt-2 pb-2">
    <div class="d-flex flex-column">
        <div class="d-flex flex-row justify-content-center gap-4">
            <div class="about-me w-100 gap-2">
                <p class="fs-6 fw-normal text-dark">About Me</p>
                <mat-form-field appearance="outline" class="w-100">
                    <textarea matInput placeholder="Write somethings about you..."></textarea>
                </mat-form-field>
            </div>
            <div class="d-flex flex-column align-items-center">
                <img 
                src="assets/images/profile-pic.jpeg"
                class="rounded-circle object-fit-cover" width="100" height="100">
                <input #fileInput type="file" (change)="onFileSelected($event)" style="display: none;">
                <button mat-icon-button (click)="fileInput.click()">
                    <mat-icon>cloud_upload</mat-icon>
                </button>
            </div>
        </div>
        <mat-divider class="w-100 mt-2 mb-2"></mat-divider>
        <div class="d-flex flex-column justify-content-center gap-2 mt-2">
            <div class="d-flex flex-row gap-4">
                <div class="d-flex flex-column w-100">
                    <p class="fs-6 fw-normal m-0 text-dark w-100 pb-1">Name</p>
                    <mat-form-field appearance="outline" class="w-100">
                        <mat-icon matPrefix>person</mat-icon>
                        <input matInput placeholder="First Name">
                    </mat-form-field>
                </div>
                <div class="d-flex flex-column w-100">
                    <p class="fs-6 fw-normal m-0 text-dark w-100 pb-1">Last Name</p>
                    <mat-form-field appearance="outline" class="w-100">
                        <mat-icon matPrefix>person</mat-icon>
                        <input matInput placeholder="Last Name">
                    </mat-form-field>
                </div>
                <div class="d-flex flex-column w-100">
                    <p class="fs-6 fw-normal m-0 text-dark w-100 pb-1">Gender</p>
                    <mat-form-field appearance="outline" class="w-100">
                        <mat-icon matPrefix>face</mat-icon>
                        <mat-select placeholder="Gender">
                            <mat-option>Male</mat-option>
                            <mat-option>Female</mat-option>
                            <mat-option>I don't prefer to say</mat-option>
                        </mat-select>
                    </mat-form-field>
                </div>
            </div>
            <div class="d-flex flex-row gap-4">
                <div class="d-flex flex-column w-100">
                    <p class="fs-6 fw-normal m-0 text-dark w-100 pb-1">Email</p>
                    <mat-form-field appearance="outline" class="w-100">
                        <mat-icon matPrefix>email</mat-icon>
                        <input matInput placeholder="Email">
                    </mat-form-field>
                </div>
                <div class="d-flex flex-column w-100">
                    <p class="fs-6 fw-normal m-0 text-dark w-100 pb-1">Phone</p>
                    <mat-form-field appearance="outline" class="w-100">
                        <mat-icon matPrefix>phone</mat-icon>
                        <input matInput placeholder="Phone">
                    </mat-form-field>
                </div>
            </div>
            <div class="d-flex flex-row gap-4">
                <div class="d-flex flex-column w-100">
                    <p class="fs-6 fw-normal m-0 text-dark w-100 pb-1">City</p>
                    <mat-form-field appearance="outline" class="w-100">
                        <mat-icon matPrefix>location_city</mat-icon>
                        <input matInput placeholder="City">
                    </mat-form-field>
                </div>
                <div class="d-flex flex-column w-100">
                    <p class="fs-6 fw-normal m-0 text-dark w-100 pb-1">Country</p>
                    <mat-form-field appearance="outline" class="w-100">
                        <mat-icon matPrefix>public</mat-icon>
                        <input matInput placeholder="Country">
                    </mat-form-field>
                </div>
            </div>
        </div>
        <div class="d-flex justify-content-end">
            <button mat-raised-button color="primary" class="mt-2">Save Changes</button>
        </div>
    </div>
</div>
