// FrontendReact/together-app/src/routes/MyProfile/ContentTabs/MyEquipments/components/EquipmentCard/EquipmentCard.tsx
import { UserEquipment } from "../../../../../../api/models/UserEquipment";
import { Card, Divider } from "@mui/material";
import IconButton from "@mui/material/IconButton";
import DeleteIcon from "@mui/icons-material/Delete";
import { deleteUserEquipment } from "../../../../../../api/services/UserEquipmentService";
import "./EquipmentCard.css";

export function EquipmentCard(equipment: UserEquipment) {
  const handleDelete = () => {
    console.log(equipment.userEquipmentId);
    deleteUserEquipment(equipment.userEquipmentId);
  };

  return (
    <Card
      sx={{ width: "177px", height: "235px" }}
      variant="outlined"
      className="mat-card rounded-2"
    >
      <div className="text-center mt-3">
        <img
          className="rounded-3 shadow p-2"
          src="https://getrentacar.com/storage/cache/images/960-640-100-fit-111601.jpeg"
          width="125"
          height="125"
          alt="equipment"
          style={{ objectFit: "cover" }}
        />
      </div>
      <Divider className="mt-3" />
      <p className="fs-6 fw-normal text-center text-dark p-3 pb-0 mb-1">
        {equipment.equipmentName}
      </p>
      <p className="fw-light text-center text-dark p-0 m-0">
        {equipment.sportId}
      </p>
      <div className="button-container d-flex flex-row gap-3">
        <IconButton aria-label="delete" className="delete-button" onClick={() => handleDelete()}>
          <DeleteIcon className="button-icon" />
        </IconButton>
      </div>
    </Card>
  );
}

// Frontend/togetherapp/src/app/my-equipments/components/equipment-card.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatCardModule } from '@angular/material/card';
import { MatDividerModule } from '@angular/material/divider';
import { MatIconModule } from '@angular/material/icon';
import { MatDialog } from '@angular/material/dialog';
import { MatButtonModule } from '@angular/material/button';

@Component({
  selector: 'togetherapp-equipment-card',
  standalone: true,
  imports: [CommonModule, MatCardModule, MatDividerModule, MatIconModule, MatButtonModule],
  templateUrl: './equipment-card.component.html',
  styleUrl: './equipment-card.component.scss',
})
export class EquipmentCardComponent implements OnInit {
  @Input() header: string | undefined;
  @Input() description: string | undefined;
  @Input() icon: string | undefined;

  constructor(public dialog: MatDialog) { }

  ngOnInit() {
    console.log('EquipmentCardComponent initialized');
  }


  deleteEquipment() {
    console.log('Delete equipment');
  }
}

<mat-card class="mat-card rounded-2" style="width: 177px; height: 250px;">
    <div class="text-center mt-3">
        <img class="rounded-3 shadow p-2" [src]="icon" width="125" height="125">
    </div>
    <mat-card-content>
        <mat-divider class="mt-3"></mat-divider>
        <p class="fs-6 fw-normal text-center text-dark p-3 pb-0 mb-1">{{header}}</p>
        <p class="fw-light text-center text-dark p-0 m-0">{{description}}</p>
    </mat-card-content>
    <div class="button-container d-flex flex-row gap-3">
        
        <button mat-mini-fab class="edit-button" (click)="deleteEquipment()">
            <mat-icon>delete</mat-icon>
        </button>
    </div>
</mat-card>
